# Post settings
collections:
    Posts:
        output: true
        permalink: /posts/:title/

future: true
excerpt_separator: <!--more-->
markdown: kramdown
highlighter: rouge
theme: minima

# Blog information
title: Eric Miller's Website
description: >
    My personal website. A place for my stuff.
email: millere@msoe.edu
github_username: sosheskaz
favicon: /files/images/favicon.png

# My image folder
my_images_path: files/images/my/
post_images_path: files/images/posts/

# configuration
gems: ["octopress-paginate" , "jekyll-seo-tag"]
exclude:    ["default.gems" , "Gemfile" , "Gemfile.lock" , ".gitignore" , "license" , ".git" , "readme.md"]
keep_files: [".git" , "license.html" , "readme.md"]
source: .
destination: ./site
layouts_dir: _layouts
markdown_ext: "md"
liquid:
    error_mode: strict

# Blog Address configs
baseurl: ""
url: "http://sosheskaz.github.io"

# baseurl: ""
# url: "http://localhost:4000"
